# Домашнее задание к семинару 01 (HW01)
## Тема: настройка рабочей среды, работа с Git, структура репозитория и базовые операции в NumPy

**Содержание:**
- Примеры создания массивов
- Размерность Numpy массивов
- Примеры индексирования и срезов
- Примеры векторных операций и базовых статистик

---

### Примеры создания массивов

In [1]:
# импорт библиотеки
import numpy as np

In [2]:
# создание массива Numpy с помощью списка
np.array([[14, -2, 11],
          [-18, 0, 0],
          [0.24, 11, -0.0014],
          [546, 546, 34343]], 
          dtype=np.float32)

array([[ 1.4000e+01, -2.0000e+00,  1.1000e+01],
       [-1.8000e+01,  0.0000e+00,  0.0000e+00],
       [ 2.4000e-01,  1.1000e+01, -1.4000e-03],
       [ 5.4600e+02,  5.4600e+02,  3.4343e+04]], dtype=float32)

In [3]:
# создание массива целых чисел Numpy с помощью списка
np.array([[14, -2, 11],
          [-18, 0, 0],
          [0.24, 11, -0.0014],
          [546, 546, 34343]], 
          dtype=np.int32)

array([[   14,    -2,    11],
       [  -18,     0,     0],
       [    0,    11,     0],
       [  546,   546, 34343]], dtype=int32)

In [4]:
# создание единичной матрицы 4x4
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
# создание многомерного Numpy массива нулей 2x11x5
np.zeros(shape=(2, 11, 5), dtype=np.int8)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

In [6]:
# создание многомерного Numpy массива единиц 2x3x4x5
np.ones(shape=(2, 3, 4, 5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [7]:
# создание Numpy массива в виде последовательности чисел с плавающей точкой
# от -10 включительно до 52 с шагом 3.5
np.arange(-10, 52, 3.5, dtype=np.float16)

array([-10. ,  -6.5,  -3. ,   0.5,   4. ,   7.5,  11. ,  14.5,  18. ,
        21.5,  25. ,  28.5,  32. ,  35.5,  39. ,  42.5,  46. ,  49.5],
      dtype=float16)

In [8]:
# Создадим Numpy массив размерности (3, 6), состоящий из мусорных данных из памяти
np.empty(shape=(3, 6))

array([[6.23042070e-307, 8.01089061e-307, 6.23058028e-307,
        2.33646676e-307, 2.78145267e-307, 8.90071985e-308],
       [8.34441742e-308, 1.95821439e-306, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 8.01097889e-307,
        1.78020848e-306, 1.42420345e-306, 8.34451928e-308]])

In [9]:
np.sin(np.empty(shape=(3, 6), dtype=np.double)).round(4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

---

### Размерность Numpy массивов
(некоторые типы данных уже были рассмотренны при создании массивов)

In [10]:
# создадим Numpy массив в виде первых 100 натуральных чисел и узнаем его размерность
my_pretty_array = np.arange(1, 101)

print(f"Созданный массив: \n {my_pretty_array} \n")
print(f"Размерность массива: {my_pretty_array.shape}")
print(f"Кол-во элементов массива {len(my_pretty_array)}")

Созданный массив: 
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

Размерность массива: (100,)
Кол-во элементов массива 100


In [11]:
# рассмотрим новые массивы, полученные изменением размерности исходного
print(f"Массив из 5 строк и 20 столбцов: \n {my_pretty_array.reshape((5, 20))} \n")
print(f"Размерность: {my_pretty_array.reshape((5, 20)).shape}")

Массив из 5 строк и 20 столбцов: 
 [[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]] 

Размерность: (5, 20)


In [12]:
print(f"3D массив из 5 матриц размера 5x4: \n {my_pretty_array.reshape((5, 5, 4))} \n")

print(f"Размерность: {my_pretty_array.reshape((5, 5, 4)).shape}")

3D массив из 5 матриц размера 5x4: 
 [[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]
  [ 13  14  15  16]
  [ 17  18  19  20]]

 [[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]
  [ 33  34  35  36]
  [ 37  38  39  40]]

 [[ 41  42  43  44]
  [ 45  46  47  48]
  [ 49  50  51  52]
  [ 53  54  55  56]
  [ 57  58  59  60]]

 [[ 61  62  63  64]
  [ 65  66  67  68]
  [ 69  70  71  72]
  [ 73  74  75  76]
  [ 77  78  79  80]]

 [[ 81  82  83  84]
  [ 85  86  87  88]
  [ 89  90  91  92]
  [ 93  94  95  96]
  [ 97  98  99 100]]] 

Размерность: (5, 5, 4)


In [13]:
# Рассмотрим массивы с N измерениями, где N-1 измерений заданы, 
# а одно определяется автоматически с помощью -1
print(f"Массив размерности {my_pretty_array.reshape((-1, 1)).shape}: \n {my_pretty_array.reshape((-1, 1))} \n")


Массив размерности (100, 1): 
 [[  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [ 12]
 [ 13]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [ 30]
 [ 31]
 [ 32]
 [ 33]
 [ 34]
 [ 35]
 [ 36]
 [ 37]
 [ 38]
 [ 39]
 [ 40]
 [ 41]
 [ 42]
 [ 43]
 [ 44]
 [ 45]
 [ 46]
 [ 47]
 [ 48]
 [ 49]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 57]
 [ 58]
 [ 59]
 [ 60]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 93]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]] 



In [14]:
print(f"Массив размерности {my_pretty_array.reshape((10, -1, 10)).shape}: \n {my_pretty_array.reshape((10, -1, 10))} \n")

Массив размерности (10, 1, 10): 
 [[[  1   2   3   4   5   6   7   8   9  10]]

 [[ 11  12  13  14  15  16  17  18  19  20]]

 [[ 21  22  23  24  25  26  27  28  29  30]]

 [[ 31  32  33  34  35  36  37  38  39  40]]

 [[ 41  42  43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66  67  68  69  70]]

 [[ 71  72  73  74  75  76  77  78  79  80]]

 [[ 81  82  83  84  85  86  87  88  89  90]]

 [[ 91  92  93  94  95  96  97  98  99 100]]] 



In [15]:
print(f"Массив размерности {my_pretty_array.reshape((1, -1, 5)).shape}: \n {my_pretty_array.reshape((1, -1, 5))} \n")

Массив размерности (1, 20, 5): 
 [[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]
  [ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]] 



In [16]:
try:
    print(f"Пример использования более одной неизвестной размерности: \
      \n {my_pretty_array.reshape((-1, -1, 5))}")
except ValueError as e:
    print(e.args)

try:
    print(f"Пример невозможного изменения размерности: \
      \n {my_pretty_array.reshape((5, 5, 5))}")
except ValueError as e:
    print(e.args)

('can only specify one unknown dimension',)
('cannot reshape array of size 100 into shape (5,5,5)',)


---

### Примеры индексирования и срезов

In [17]:
# Отдельные элементы и срезы будем брать из my_pretty_array
# с изменённой размерностью (1, 20, 5)
my_pretty_array = my_pretty_array.reshape((1, -1, 5))
print(my_pretty_array.dtype, "\n", my_pretty_array)

int64 
 [[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]
  [ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]]


In [18]:
print(f"Первый элемент последней строки: {my_pretty_array[0][-1][0]}")
print(f"Первая строка: {my_pretty_array[0, 0]}")
print(f"Второй столбец с конца: {my_pretty_array[0, :, -2]}")
print(f"Медиана десятой строки: {my_pretty_array[0, 9, my_pretty_array.shape[-1]//2]}")
print(f"Трейий и пятый элементы каждой чётной строки: \n {my_pretty_array[0, ::2, 2::2]}")

Первый элемент последней строки: 96
Первая строка: [1 2 3 4 5]
Второй столбец с конца: [ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99]
Медиана десятой строки: 48
Трейий и пятый элементы каждой чётной строки: 
 [[ 3  5]
 [13 15]
 [23 25]
 [33 35]
 [43 45]
 [53 55]
 [63 65]
 [73 75]
 [83 85]
 [93 95]]


In [19]:
try:
    print(f"Пример некорректного индекса: \
      \n {my_pretty_array[0, 0.5]}")
except IndexError as e:
    print(e.args)

('only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices',)


---

### Примеры векторных операций и базовых статистик

In [20]:
# в качестве массива для преобразования возьмём срез my_pretty_array
my_new_pretty_array = my_pretty_array[0, ::3, ::2]
my_new_pretty_array

array([[ 1,  3,  5],
       [16, 18, 20],
       [31, 33, 35],
       [46, 48, 50],
       [61, 63, 65],
       [76, 78, 80],
       [91, 93, 95]])

In [21]:
# результат применения тригонометрических функций
print(f"Синус: \n {np.sin(my_new_pretty_array)}")
print(f"Гиперболический тангенс: \n {np.tanh(my_new_pretty_array)}")
print(f"Гиперболический арксинус: \n {np.arcsinh(my_new_pretty_array)}")
print(f"Арккосинус: \n {np.arccosh(my_new_pretty_array)}")

Синус: 
 [[ 0.84147098  0.14112001 -0.95892427]
 [-0.28790332 -0.75098725  0.91294525]
 [-0.40403765  0.99991186 -0.42818267]
 [ 0.90178835 -0.76825466 -0.26237485]
 [-0.96611777  0.1673557   0.82682868]
 [ 0.56610764  0.51397846 -0.99388865]
 [ 0.10598751 -0.94828214  0.68326171]]
Гиперболический тангенс: 
 [[0.76159416 0.99505475 0.9999092 ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]]
Гиперболический арксинус: 
 [[0.88137359 1.81844646 2.31243834]
 [3.46671104 3.58428965 3.68950387]
 [4.12739443 4.18988423 4.24869926]
 [4.5219067  4.56445668 4.60527017]
 [4.80408822 4.83634489 4.86759362]
 [5.0239238  5.0498971  5.07521288]
 [5.20403688 5.22577558 5.24705177]]
Арккосинус: 
 [[0.         1.76274717 2.29243167]
 [3.46475791 3.58274644 3.68825387]
 [4.12687414 4.18942509 4.2482911 ]
 [4.52167041 4.56423967 4.60507017

In [22]:
# базовые статистики
print(f"Среднее каждой строки: \n {np.mean(my_new_pretty_array, axis=1)}")
print(f"Медиана каждой строки: \n {np.median(my_new_pretty_array, axis=1)}")
print(f"Стандартное отклонение для каждого столбца: \n {np.std(my_new_pretty_array, axis=0)}")
print(f"Сумма по каждой строке: \n {np.sum(my_new_pretty_array, axis=1)}")
print(f"Сумма по всему массиву: \n {np.sum(my_new_pretty_array)}")
print(f"Максимум по каждой строке: \n {np.max(my_new_pretty_array, axis=1)}")

Среднее каждой строки: 
 [ 3. 18. 33. 48. 63. 78. 93.]
Медиана каждой строки: 
 [ 3. 18. 33. 48. 63. 78. 93.]
Стандартное отклонение для каждого столбца: 
 [30. 30. 30.]
Сумма по каждой строке: 
 [  9  54  99 144 189 234 279]
Сумма по всему массиву: 
 1008
Максимум по каждой строке: 
 [ 5 20 35 50 65 80 95]


In [23]:
# некоторые операции с массивами
print(f"Сложение (поэлементно): \n {my_new_pretty_array + np.sin(my_new_pretty_array)}\n")
print(f"Умножение (поэлементно): \n {my_new_pretty_array * np.pow(my_new_pretty_array, 2)}\n")
print(f"Объединение по столбцам: \n {np.hstack([my_new_pretty_array, -0.25*my_new_pretty_array])}\n")
print(f"Объединение по строкам: \n {np.vstack([np.sin(my_new_pretty_array), np.pow(my_new_pretty_array, 2)]).round(4)}\n")
print(f"Умножение (векторное): \n {my_new_pretty_array @ my_new_pretty_array.reshape(3, -1)}")

Сложение (поэлементно): 
 [[ 1.84147098  3.14112001  4.04107573]
 [15.71209668 17.24901275 20.91294525]
 [30.59596235 33.99991186 34.57181733]
 [46.90178835 47.23174534 49.73762515]
 [60.03388223 63.1673557  65.82682868]
 [76.56610764 78.51397846 79.00611135]
 [91.10598751 92.05171786 95.68326171]]

Умножение (поэлементно): 
 [[     1     27    125]
 [  4096   5832   8000]
 [ 29791  35937  42875]
 [ 97336 110592 125000]
 [226981 250047 274625]
 [438976 474552 512000]
 [753571 804357 857375]]

Объединение по столбцам: 
 [[  1.     3.     5.    -0.25  -0.75  -1.25]
 [ 16.    18.    20.    -4.    -4.5   -5.  ]
 [ 31.    33.    35.    -7.75  -8.25  -8.75]
 [ 46.    48.    50.   -11.5  -12.   -12.5 ]
 [ 61.    63.    65.   -15.25 -15.75 -16.25]
 [ 76.    78.    80.   -19.   -19.5  -20.  ]
 [ 91.    93.    95.   -22.75 -23.25 -23.75]]

Объединение по строкам: 
 [[ 8.415e-01  1.411e-01 -9.589e-01]
 [-2.879e-01 -7.510e-01  9.129e-01]
 [-4.040e-01  9.999e-01 -4.282e-01]
 [ 9.018e-01 -7.683e-01 

In [24]:
try:
    print(f"Пример некорректного векторного умножения (несоместимые размерности): \
      \n {my_new_pretty_array @ my_new_pretty_array}")
except ValueError as e:
    print(e.args)

('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 7 is different from 3)',)
